spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://springboot-webservice.cnndhf7x7pwl.ap-northeast-2.rds.amazonaws.com:3306/springboot_webservice
    username: shkim
    password: dndzidznD1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html